### ISSUE TITLE
Include 'bskye' in supported embed providers

### ISSUE THREAD

**Issue by SalbugVR** [Kyanoxia/skycord#2]
In my experience, `bskye.app` has been my preferred and, honestly, most recommended option amongst the current third-party embed providers. Including it in the list would be really helpful.

**Comment by SalbugVR** [comment]
For example, `bskye.app` has gif support.

https://github.com/user-attachments/assets/84c60b63-cfba-441b-b611-3adb58a15260

**Comment by Kyanoxia** [comment]
I'll run tests later today, expect an update on the issue by Monday night.

**Comment by Kyanoxia** [comment]
Bskye has the same functionality as VixBsky.  Both have gif support, video support, and text support (obviously lol).  Closing as I won't add it any time soon.  Feel free to reopen if any functional superiority to VixBsky (our recommend provider) is observed.

**Comment by SalbugVR** [comment]
I just tested, and VixBsky doesn't support gifs on quoted posts while bskye does. If you could reconsider, that might be nice. Meanwhile I'll report this on the VixBsky repo.

![image](https://github.com/user-attachments/assets/d6c46358-fe93-45ce-847d-80035898a59a)

**Comment by SalbugVR** [comment]
Referenced here: https://github.com/Rapougnac/VixBluesky/issues/23

**Comment by Kyanoxia** [comment]
Ah I see.
You know what fuck it, might as well.  I'll have it updated by Monday night at the latest (more realistically tonight)

**Comment by Kyanoxia** [comment]
Added in tonight's update.
