### ISSUE TITLE
Feedback: Filter System based on keywords and/or hashtags

### ISSUE THREAD

**Issue by SalbugVR** [Kyanoxia/skycord#3]
Currently, the bot automatically embeds any post to a channel, regardless of context. Implementing a system that filters posts based on keywords or hashtags would be a helpful addition for cases where certain posts should not be auto-posted.

**Comment by Kyanoxia** [comment]
Very possible to do with a regex that scans the post body or the json api response to allow for images as a filter as well, but for something like this I won't worry about polishing it too much as it's for advanced users.

We'll see how engagement [here](https://bsky.app/profile/skycord.kyanoxia.com/post/3lamtr22suc2h) goes before I spend time implementing this.  You're more than welcome to create a pull request to implement this as well if you want.

**Comment by SalbugVR** [comment]
> You're more than welcome to create a pull request to implement this as well if you want.

I definitely would if I could but I'm much more of a UX / ideas person then I am a programmer. ^^;

**Comment by Kyanoxia** [comment]
> > You're more than welcome to create a pull request to implement this as well if you want.
> 
> I definitely would if I could but I'm much more of an ideas person then I am a programmer. ^^;

Hey that's totally fine, that's why I'm here!  I'm getting started on it soon, I'd expect it to be in local testing by the weekend and pushed next week.

**Comment by Kyanoxia** [comment]
Added regex blacklist in commit #aaef7c9, Skycord version 1.3.6.
I opted for a regex solution because it's much more versatile than just tags or keywords.  The user can set their own filter including arguments such as `/i` and `/g` when they reconnect.
