### ISSUE TITLE
Refine invalid account detection to account for invalid responses

### ISSUE THREAD

**Issue by imnewhere24** [Kyanoxia/skycord#4]
Tonight at around 9:20 CST, a bunch of my bots suddenly disconnected. To add, I often have to wait 5-10 minutes for the bot to add the latest post from the account. Sometimes, the bot never connects to an account and I have to try multiple times.

**Comment by Kyanoxia** [comment]
Issue should be resolved now, and was due to the BlueSky API going down last night.  It's since gone back up and as such, I'll be shifting the focus of this issue to a more robust invalid account detection system.

https://bsky.app/profile/skycord.kyanoxia.com/post/3lbf53te5ps2m

**Comment by Kyanoxia** [comment]
I was overthinking it and just needed to check errors for a certain code (silly me)
