### ISSUE TITLE
Provider Change Not Updating

### ISSUE THREAD

**Issue by SalbugVR** [Kyanoxia/skycord#6]
Despite setting the provider back to `bsky.app` (as the native provider has become much more robust), the app still uses `bskye.app` even after reconnecting my social account. The provider does not update as expected.

![image](https://github.com/user-attachments/assets/6a541762-7dd9-4f04-99d6-37a2c6b8a0b7)

**Comment by Kyanoxia** [comment]
Alright go ahead and try now and see if the issue persists.

Keep in mind you can't update a single property yet so any field that is not filled out will be set to the default value.

**Comment by SalbugVR** [comment]
Ah yeah, it's good now.

![image](https://github.com/user-attachments/assets/8fe8f3d9-b1c1-433c-96da-a0d051857c59)
